[[redirects]]
  from = "/api/property/*"
  to = "/.netlify/functions/get-single-property?id=:splat"
  status = 200

[[redirects]]
  from = "/api/properties"
  to = "/.netlify/functions/get-all-properties"
  status = 200

[[redirects]]
  from = "/api/submit-enquiry"
  to = "/.netlify/functions/submit-enquiry"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
